### ISSUE TITLE
Angular 16 - Ivy

### ISSUE THREAD

**Issue by canadakickass** [Tinkoff/ng-event-plugins#57]
Angular 16 will fully deprecate ngcc, making this librairy no longer usable in Angular 16+. 

Request: Make ng-event-plugins work on Angular 16+

Thanks

**Comment by waterplea** [comment]
This library is built with Ivy on Angular 12 and is compatible with Angular 16+:
https://stackblitz.com/edit/stackblitz-starters-sevaoa

Are you seeing any issues in your app with Angular 16?

**Comment by canadakickass** [comment]
Ah ok good. I haven't tested it on angular 16. But when I compile my project in v15, I see that it is using ngcc to compile some files in the ng-event-plugins node_module repo so I thought it might become problematic once I migrate to v16

Thanks
